### ISSUE TITLE
Error with excavator - digital signature

### ISSUE THREAD

**Issue by happyartifact** [nicehash/NiceHashMiner2#80]
[18:51:06][0x0000133c][info] Log started
[18:51:07][0x0000133c][error] opencl | Failed to load AMD Display Library.
[18:51:07][0x0000133c][error] opencl | Failed to initialize AMD Display Library.
[18:51:07][0x0000133c][error] opencl | Failed to load phymem.
[18:51:07][0x0000133c][error] opencl | Please disable driver signature enforcement and run miner as administrator.
[18:51:07][0x0000133c][info] core | Found CUDA device: GeForce GTX 1060 6GB
[18:51:07][0x0000133c][info] api | Listening on 127.0.0.1:3456
[18:51:07][0x0000133c][info] core | Initialized!

**Comment by happyartifact** [comment]
Discussed here https://github.com/nicehash/NiceHashMiner2/issues/79

**Comment by Crypto-Lord** [comment]
@happyartifact you will need to disable windows automatic settings for blocking driver signature for 'phymem' to install. Link below provides you with 2 options for disabling it (1 temporarily till you reboot, the other permanently until you re-enable)
 
http://windowsreport.com/driver-signature-enforcement-windows-10/

**Comment by happyartifact** [comment]
Ok I disabled as instructed, restarted, and launched .7.  The computer then crashed while launching excavator.  And it crashed so hard it's not coming back up.  I don't know what happened here, but this sucks.  Going to try reinstalling win 7.

**Comment by Squall-Leonhart** [comment]
driver signing on my rig is always off, the phymem driver does NOT install.

**Comment by happyartifact** [comment]
I was able to quickly repair it, but it messed up the windows boot.  It also messed up the nVidia drivers, requiring a reinstall.

**Comment by S74nk0** [comment]
@happyartifact If you do not have AMD GPUs on that rig ignore this. Also if you do have AMD rigs you can also ignore this since algorithms that require this driver are currently hidden from NHM2.

**Comment by fefsf** [comment]
Does this error also relate to windows defender blocking extractor on the latest beta? I have nvidia GPUs and one of my rigs started to block it, so i had to disable windows defender completely.

**Comment by Crypto-Lord** [comment]
@fefsf You can set exclusions in windows defender, that may solve the problem without disabling defender altogether. Also certain antivirus software blocks or removes parts of the mining software thinking its malware.

**Comment by fefsf** [comment]
@Crypto-Lord Yeah, i added an exception to the entire NHM directory, however, when NHM v2 downloads  the updated excavator server it must temporarily move it to another location because windows defender still blocked it.

**Comment by S74nk0** [comment]
The new soon to be released **excavator** version will have the signed driver. You don't need to disable anything to install it as the currently enabled algorithms do not require the driver to work.

**Comment by computeronix** [comment]
Looks like this is now resolved on the new 2.0.0.7 since the driver is signed

**Comment by ZenoDiac** [comment]
@S74nk0 I just received the same error today as @happyartifact - it's strange cause I have GTX 980 TI that ran fine last night. When I came home today, the PC was shut down (same time as NiceHash payout, exactly 12h according to the system logs) When I ran NHM2 again, I got this error.  I can't disable driver sigs because Secure Boot policy blocks it (this can't be disabled). 
Why would this happen now? And do you think the new excavator version could solve this problem? I am currently stuck and can't mine...

**Comment by ZenoDiac** [comment]
Actually, I found a temporary way around this for v .07: Edit the General.json file in the config and set DisableDetectionAMD = True. This is if you have a Nvidia card like OP and I, 
Although this seems to reset every time you restart the program.

**Comment by burninghey** [comment]
Running R9 290X here. When starting NHM2.0.0.7 with admin privileges (as proposed) my computer windows 7 64 (visual basic installed) crashes into bluescreen - exactly when starting excavator.
Disabling driver signature enforcement did not solve this; it's still failing to load phymen.

**Comment by S74nk0** [comment]
**excavator** from **v1.2.7a** has a signed driver. NiceHash Miner v2.0.0.7 will update to **excavator** to **v1.2.8a**
Closing issue...
@burninghey Please open a new issue regarding your problem. We will address it there.
